In [1]:
#The required libraries are imported at the beginning of the program.
#Pandas is used for handling datasets.
import pandas as pd

In [3]:
#Load the dataset is loaded into the dataset variable using a CSV file.
dataset = pd.read_csv("insurance_pre.csv")
#print dataset and Understand the Dataset
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [4]:
# Convert categorical columns to numeric
dataset = pd.get_dummies(dataset, drop_first=True)
#print dataset  
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400     False        True
1      18  33.770         1   1725.55230      True       False
2      28  33.000         3   4449.46200      True       False
3      33  22.705         0  21984.47061      True       False
4      32  28.880         0   3866.85520      True       False
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830      True       False
1334   18  31.920         0   2205.98080     False       False
1335   18  36.850         0   1629.83350     False       False
1336   21  25.800         0   2007.94500     False       False
1337   61  29.070         0  29141.36030     False        True

[1338 rows x 6 columns]

In [5]:
#print dataset columns
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [6]:
#This step prepares the data for training.
# Assign input to independant Variable
independant = dataset[["age", "bmi", "children",  "sex_male","smoker_yes"]]
#print independant variable
independant

      age     bmi  children  sex_male  smoker_yes
0      19  27.900         0     False        True
1      18  33.770         1      True       False
2      28  33.000         3      True       False
3      33  22.705         0      True       False
4      32  28.880         0      True       False
...   ...     ...       ...       ...         ...
1333   50  30.970         3      True       False
1334   18  31.920         0     False       False
1335   18  36.850         0     False       False
1336   21  25.800         0     False       False
1337   61  29.070         0     False        True

[1338 rows x 5 columns]

In [7]:
# Assign output to dependendant Variable
dependendant =dataset[["charges"]]
#print dependendant variable
dependendant

          charges
0     16884.92400
1      1725.55230
2      4449.46200
3     21984.47061
4      3866.85520
...           ...
1333  10600.54830
1334   2205.98080
1335   1629.83350
1336   2007.94500
1337  29141.36030

[1338 rows x 1 columns]

In [8]:
#The data is divided into: Training data and Testing data
#The training data is used to build the model and testing data is used to evaluate model performance.
#To do this we are using sklearn. sklearn.model_selection imports the train_test_split function so you can use it to split your data into training and testing sets.
from sklearn.model_selection import train_test_split
#print train_test_split
train_test_split

In [14]:
# The below line of code splits data into 4 parts:
# x_train = input features for training , x_test = input features for testing
# y_train = target/output for training ,  y_test = target/output for testing
# And the options mean: test_size=0.30 → 30% of the data goes to test, 70% to train
# random_state=0 → keeps the split same every time you run it (for repeatable results)
#So Split independant and dependendant into train/test sets (70/30) in a repeatable way.   
x_train,x_test,y_train,y_test=train_test_split(independant, dependendant, test_size=0.30, random_state=0)

In [19]:
y_train
Y = y_train.values.ravel()
Y

array([ 2200.83085,  5649.715  , 12592.5345 ,  7419.4779 ,  5261.46945,
        1744.465  , 36898.73308, 13143.86485,  6781.3542 , 12981.3457 ,
        8556.907  , 12479.70895, 48824.45   ,  3443.064  ,  7935.29115,
       16586.49771, 14590.63205,  1532.4697 ,  6933.24225,  2217.46915,
       11856.4115 , 19214.70553, 11534.87265, 40974.1649 ,  4889.0368 ,
       33907.548  , 16776.30405, 10982.5013 ,  8026.6666 , 44501.3982 ,
        8280.6227 ,  3736.4647 ,  9058.7303 , 18767.7377 , 36197.699  ,
       19107.7796 , 25656.57526, 39125.33225,  3906.127  , 17085.2676 ,
        3021.80915, 36397.576  ,  4449.462  , 11396.9002 ,  1622.1885 ,
       41919.097  ,  8944.1151 ,  4391.652  ,  4005.4225 ,  8930.93455,
        9447.25035,  7731.85785, 11576.13   ,  3757.8448 ,  2154.361  ,
        3056.3881 ,  3956.07145,  7526.70645, 34439.8559 , 12928.7911 ,
        7152.6714 , 26236.57997, 11743.9341 ,  1769.53165, 10825.2537 ,
       10796.35025,  4296.2712 ,  1632.03625, 44202.6536 ,  7623.518  ,
       28340.18885,  3594.17085, 24513.09126,  5488.262  , 11842.442  ,
       17748.5062 , 33900.653  ,  9566.9909 ,  8017.06115,  1711.0268 ,
        4239.89265,  8302.53565,  2130.6759 ,  9855.1314 ,  1743.214  ,
        3392.3652 , 40103.89   ,  6250.435  ,  7265.7025 ,  3989.841  ,
       21195.818  , 10407.08585, 12797.20962,  4934.705  ,  6123.5688 ,
        4915.05985,  1534.3045 ,  8703.456  , 21677.28345,  5116.5004 ,
       46200.9851 ,  9957.7216 ,  6775.961  ,  3046.062  ,  6360.9936 ,
       39722.7462 ,  1906.35825, 11737.84884,  8835.26495,  8520.026  ,
        2217.6012 , 11938.25595, 13047.33235, 35585.576  , 12124.9924 ,
        7443.64305, 13393.756  , 14254.6082 , 36307.7983 ,  8023.13545,
       11353.2276 , 20462.99766,  3645.0894 , 35595.5898 ,  4673.3922 ,
       19350.3689 , 18806.14547,  4399.731  , 10560.4917 , 10579.711  ,
        5397.6167 ,  1967.0227 ,  1146.7966 ,  1639.5631 ,  3227.1211 ,
        1731.677  , 13430.265  ,  3213.62205,  7348.142  ,  9048.0273 ,
       11743.299  ,  6571.02435, 12557.6053 ,  2196.4732 ,  9174.13565,
        5138.2567 ,  7421.19455, 12363.547  , 11840.77505, 20745.9891 ,
       13063.883  ,  8062.764  ,  7256.7231 , 26392.26029,  5385.3379 ,
       11033.6617 ,  7077.1894 ,  5266.3656 , 21880.82   , 10713.644  ,
        9634.538  , 12913.9924 , 10269.46   ,  5125.2157 ,  3484.331  ,
        5080.096  ,  6402.29135,  1704.70015,  7243.8136 ,  3201.24515,
        5267.81815, 12235.8392 ,  3554.203  ,  3766.8838 ,  2219.4451 ,
        2302.3    ,  4347.02335, 18157.876  , 22395.74424, 36950.2567 ,
       12957.118  ,  9872.701  , 44423.803  ,  1634.5734 , 12430.95335,
        1615.7667 ,  5253.524  , 17178.6824 , 10106.13425,  5227.98875,
       13635.6379 , 10065.413  , 39597.4072 , 30166.61817,  6112.35295,
       12044.342  , 19444.2658 ,  1631.8212 ,  8604.48365,  3994.1778 ,
        1621.8827 , 24667.419  , 33307.5508 , 20781.48892, 14358.36437,
        6985.50695, 24393.6224 , 24869.8368 ,  8240.5896 , 17179.522  ,
       39774.2763 ,  4340.4409 , 23807.2406 ,  8601.3293 , 24535.69855,
       17560.37975, 12622.1795 ,  9563.029  , 16796.41194, 13228.84695,
       35160.13457,  2211.13075, 10450.552  , 11411.685  ,  2203.73595,
        6311.952  , 24873.3849 ,  1694.7964 ,  2473.3341 , 11015.1747 ,
       13143.33665,  6653.7886 ,  1121.8739 , 60021.39897,  1980.07   ,
       10977.2063 , 20177.67113,  2483.736  ,  4536.259  , 25992.82104,
       16455.70785,  6128.79745, 46599.1084 , 32108.66282, 11658.11505,
        1826.843  ,  9866.30485, 16138.76205,  5920.1041 ,  2026.9741 ,
        7418.522  , 15006.57945,  7639.41745, 11520.09985,  9095.06825,
       12646.207  ,  4134.08245,  1621.3402 ,  1515.3449 , 34806.4677 ,
        6272.4772 , 13880.949  ,  3353.284  , 41661.602  ,  1748.774  ,
        7640.3092 ,  8891.1395 , 11362.755  ,  7742.1098 ,  1728.897  ,
        6799.458  , 10923.9332 ,  8538.28845,  2416.955  , 18648.4217 ,
       12574.049  , 11381.3254 ,  2156.7518 ,  3947.4131 , 12629.8967 ,
        1984.4533 ,  3471.4096 ,  5257.50795, 13429.0354 ,  1664.9996 ,
        9182.17   ,  2801.2588 ,  2304.0022 ,  7209.4918 ,  4074.4537 ,
        2709.1119 , 12629.1656 ,  8782.469  , 47896.79135, 10085.846  ,
       38245.59327, 15518.18025, 13937.6665 ,  6770.1925 ,  4931.647  ,
        3393.35635,  8688.85885, 15230.32405,  4415.1588 ,  2710.82855,
        2897.3235 , 10436.096  ,  3761.292  , 13204.28565,  8968.33   ,
        6600.20595, 12233.828  , 27037.9141 , 11830.6072 , 11454.0215 ,
       19040.876  ,  2395.17155,  2913.569  ,  7633.7206 ,  1141.4451 ,
        6414.178  ,  1135.9407 ,  6184.2994 , 20167.33603,  8124.4084 ,
        4350.5144 ,  4032.2407 , 13405.3903 ,  3500.6123 ,  2007.945  ,
        1632.56445,  8582.3023 ,  8442.667  ,  2755.02095,  5699.8375 ,
        4889.9995 ,  8522.003  , 41676.0811 ,  4618.0799 ,  1261.859  ,
       11150.78   ,  6686.4313 ,  7144.86265, 21232.18226,  9225.2564 ,
        3693.428  ,  4149.736  , 17929.30337, 34472.841  , 12829.4551 ,
        7196.867  ,  3875.7341 ,  1625.43375, 15359.1045 ,  3943.5954 ,
        3077.0955 ,  3171.6149 , 17904.52705, 15161.5344 , 47055.5321 ,
       36580.28216, 27000.98473,  1880.07   , 17468.9839 , 11326.71487,
        6435.6237 ,  6356.2707 ,  1263.249  ,  8116.68   , 46130.5265 ,
       17352.6803 ,  2020.5523 , 13462.52   , 38282.7495 ,  5469.0066 ,
       18765.87545, 24671.66334,  7740.337  ,  8603.8234 ,  6948.7008 ,
        2850.68375, 12129.61415, 27322.73386,  3385.39915, 11881.9696 ,
       14235.072  , 15817.9857 , 14382.70905, 18259.216  , 18328.2381 ,
        6748.5912 ,  9283.562  , 43896.3763 , 10338.9316 ,  8823.279  ,
       11253.421  ,  7345.7266 ,  6186.127  ,  4661.28635, 25081.76784,
       18246.4955 , 19144.57652, 11488.31695,  1242.26   ,  5012.471  ,
        2138.0707 , 10594.2257 ,  7749.1564 ,  7153.5539 , 37607.5277 ,
        9861.025  ,  1526.312  , 24476.47851, 11244.3769 ,  5240.765  ,
       12644.589  , 10422.91665,  9411.005  ,  6666.243  ,  5003.853  ,
        1877.9294 , 49577.6624 , 14394.5579 , 12495.29085,  5584.3057 ,
        3579.8287 , 11070.535  , 14133.03775, 15828.82173, 10381.4787 ,
        1137.011  ,  1391.5287 ,  8233.0975 ,  3392.9768 ,  4779.6023 ,
       10197.7722 , 12890.05765, 16115.3045 ,  2134.9015 ,  4337.7352 ,
        4454.40265,  8027.968  , 27724.28875,  9504.3103 , 12485.8009 ,
       18033.9679 , 43753.33705,  3260.199  , 44400.4064 , 12609.88702,
        8083.9198 ,  5272.1758 ,  4076.497  , 37079.372  , 11163.568  ,
        9910.35985,  5246.047  ,  2104.1134 , 16069.08475, 20773.62775,
        3167.45585,  6358.77645,  1163.4627 , 10791.96   , 10848.1343 ,
        4237.12655,  4992.3764 , 12105.32   , 16420.49455, 14410.9321 ,
       36189.1017 , 13470.86   ,  7726.854  , 11082.5772 ,  8569.8618 ,
        8068.185  , 14449.8544 , 16884.924  , 39983.42595,  9863.4718 ,
        8964.06055, 35147.52848,  2632.992  ,  3857.75925,  3877.30425,
        8334.45755, 46661.4424 , 39727.614  , 34779.615  , 11363.2832 ,
       42760.5022 , 48673.5588 , 21344.8467 , 17043.3414 ,  3659.346  ,
       28868.6639 ,  5002.7827 , 10264.4421 ,  2155.6815 , 42111.6647 ,
       12648.7034 ,  7201.70085, 12096.6512 ,  4571.41305,  9288.0267 ,
       36124.5737 ,  6548.19505, 16450.8947 ,  9778.3472 ,  1832.094  ,
       40419.0191 , 14451.83515,  4402.233  ,  9625.92   , 18608.262  ,
        7160.094  ,  2585.269  ,  2020.177  ,  8965.79575, 21984.47061,
        2457.21115, 11657.7189 , 24603.04837, 42112.2356 , 10976.24575,
        2459.7201 ,  3704.3545 , 21259.37795,  9487.6442 ,  2221.56445,
       43813.8661 ,  7358.17565, 44641.1974 ,  4466.6214 , 11987.1682 ,
        2689.4954 , 36021.0112 ,  3481.868  ,  9748.9106 , 10072.05505,
        8232.6388 , 28950.4692 , 11289.10925, 16085.1275 , 30063.58055,
       46151.1245 ,  4686.3887 , 21774.32215, 12032.326  ,  4133.64165,
        5979.731  , 10928.849  , 10043.249  ,  4463.2051 ,  9800.8882 ,
        1628.4709 ,  4646.759  , 10704.47   ,  2904.088  , 12925.886  ,
       58571.07448,  9414.92   , 17081.08   , 33750.2918 , 10325.206  ,
       10959.6947 , 11264.541  ,  2480.9791 , 21659.9301 , 14119.62   ,
       19798.05455,  3577.999  ,  2045.68525, 38344.566  ,  7281.5056 ,
       22218.1149 , 24106.91255, 39047.285  ,  1977.815  , 27117.99378,
       12029.2867 ,  6289.7549 , 38711.     , 19594.80965,  8539.671  ,
       37829.7242 ,  9620.3307 , 12404.8791 ,  5209.57885, 19964.7463 ,
        6373.55735, 13887.204  , 13981.85035, 19442.3535 ,  2207.69745,
        3866.8552 , 22331.5668 ,  4357.04365, 13725.47184, 11931.12525,
       13607.36875,  9264.797  ,  4753.6368 , 14474.675  , 20878.78443,
       23288.9284 ,  5708.867  , 34672.1472 , 26926.5144 ,  8551.347  ,
        6986.697  ,  7624.63   ,  2438.0552 ,  5974.3847 , 13831.1152 ,
       37484.4493 ,  9875.6804 ,  8125.7845 ,  2709.24395, 11090.7178 ,
        1712.227  , 10156.7832 , 13390.559  , 13844.7972 ,  6059.173  ,
       11674.13   ,  5152.134  , 12142.5786 ,  5989.52365,  5615.369  ,
        4762.329  ,  1875.344  , 11394.06555,  2250.8352 , 13126.67745,
        5926.846  , 12741.16745,  6849.026  ,  7162.0122 , 55135.40209,
        4438.2634 ,  3861.20965,  9549.5651 ,  5478.0368 , 11286.5387 ,
        9850.432  , 11165.41765,  9101.798  ,  8527.532  , 31620.00106,
        8252.2843 ,  8823.98575, 29330.98315,  2497.0383 ,  7046.7222 ,
       48549.17835, 10096.97   ,  4234.927  , 12146.971  ,  4719.73655,
       47462.894  , 39725.51805, 21797.0004 ,  1242.816  ,  9877.6077 ,
       21348.706  , 19539.243  , 10965.446  ,  4527.18295,  2396.0959 ,
       11365.952  ,  3558.62025,  5028.1466 ,  2331.519  , 20234.85475,
       23306.547  , 41949.2441 ,  9144.565  , 15555.18875,  8211.1002 ,
       47269.854  ,  5729.0053 ,  3309.7926 , 12638.195  ,  6313.759  ,
       46113.511  , 11305.93455,  7518.02535,  1727.54   ,  2464.6188 ,
        4747.0529 , 11842.62375, 19719.6947 ,  8334.5896 ,  3292.52985,
       17663.1442 , 21082.16   , 11455.28   , 18955.22017, 10564.8845 ,
       40720.55105, 25309.489  , 38792.6856 ,  3044.2133 ,  8671.19125,
        6455.86265,  1815.8759 ,  2719.27975, 18963.17192,  4795.6568 ,
        6082.405  ,  4922.9159 ,  1261.442  , 23563.01618, 13555.0049 ,
        8516.829  ,  3172.018  , 15612.19335,  7050.642  ,  1727.785  ,
       10141.1362 , 13770.0979 , 24180.9335 , 34828.654  , 14349.8544 ,
        6600.361  , 13352.0998 , 19023.26   , 14901.5167 , 18804.7524 ,
       19496.71917, 26140.3603 , 19361.9988 ,  5245.2269 , 21978.6769 ,
       11946.6259 ,  2136.88225, 11538.421  , 19933.458  ,  1702.4553 ,
        2680.9493 ,  1136.3994 ,  6198.7518 , 34617.84065,  3537.703  ,
       12094.478  ,  5373.36425, 12224.35085, 16657.71745,  9541.69555,
       42211.1382 , 22462.04375,  6710.1919 , 24915.22085,  9704.66805,
        6389.37785,  6203.90175, 10355.641  , 11013.7119 ,  9583.8933 ,
        5630.45785, 11881.358  ,  4830.63   ,  2741.948  , 20984.0936 ,
        2523.1695 ,  4949.7587 ,  8428.0693 , 11482.63485, 14256.1928 ,
        2201.0971 ,  1705.6245 , 10600.5483 , 13470.8044 ,  6185.3208 ,
        7954.517  , 27218.43725, 41999.52   , 14001.1338 , 19673.33573,
        1842.519  , 25333.33284, 23887.6627 , 29186.48236, 27533.9129 ,
       11945.1327 ,  7441.501  ,  8798.593  ,  2166.732  ,  3062.50825,
        8627.5411 , 11566.30055, 11735.87905,  7512.267  , 25678.77845,
        3161.454  , 16297.846  , 47291.055  , 10806.839  , 24915.04626,
        9432.9253 , 48885.13561, 26109.32905,  6393.60345,  9715.841  ,
       28476.73499, 40941.2854 , 36910.60803,  4687.797  , 20420.60465,
        4151.0287 , 27941.28758, 27808.7251 ,  5966.8874 ,  5757.41345,
       43578.9394 ,  5934.3798 ,  1981.5819 ,  7050.0213 ,  5855.9025 ,
        7045.499  ,  9386.1613 ,  2494.022  ,  6610.1097 , 11093.6229 ,
       44585.45587,  5709.1644 , 39556.4945 , 14007.222  ,  6238.298  ,
       22412.6485 , 38126.2465 , 12815.44495, 37701.8768 ,  6474.013  ,
        3847.674  , 13415.0381 ,  5846.9176 ,  8871.1517 , 35069.37452,
        8116.26885,  1759.338  , 30284.64294,  2842.76075, 43921.1837 ,
        6593.5083 ,  5693.4305 ,  4827.90495,  9193.8385 , 36085.219  ,
       17496.306  , 12231.6136 ,  1252.407  , 20009.63365,  1241.565  ,
        4529.477  , 18223.4512 , 13129.60345,  2527.81865,  7228.21565,
        3208.787  , 13974.45555, 26467.09737,  7261.741  ,  2866.091  ,
       37133.8982 , 39836.519  ,  7173.35995, 15170.069  ,  6571.544  ,
       14988.432  , 10942.13205,  8988.15875, 23082.95533,  9869.8102 ,
        6338.0756 , 20277.80751, 34303.1672 ,  5400.9805 ,  1682.597  ,
       62592.87309,  8978.1851 ,  3176.8159 , 13822.803  ,  9617.66245,
        7985.815  ,  2102.2647 ,  7133.9025 , 32734.1863 ,  2103.08   ,
        2775.19215, 38415.474  ,  2585.85065, 11763.0009 ,  7222.78625,
        7789.635  , 29523.1656 ,  2457.502  , 63770.42801, 10231.4999 ,
       12949.1554 , 40273.6455 ,  7147.4728 ,  2727.3951 ,  2639.0429 ,
       22478.6    , 14394.39815,  4719.52405, 11272.33139,  8733.22925,
       15820.699  , 37270.1512 ,  5910.944  ,  5031.26955,  7804.1605 ,
       30259.99556,  7448.40395, 11741.726  , 45008.9555 ,  8825.086  ,
       10601.63225,  2855.43755, 11073.176  ,  3972.9247 ,  5375.038  ,
       34838.873  ,  1633.0444 , 11299.343  , 33471.97189,  2150.469  ,
       13747.87235,  3070.8087 ,  7160.3303 ,  5415.6612 ,  1646.4297 ,
        4766.022  ])

In [21]:
from sklearn.ensemble import AdaBoostRegressor
from sklearn.tree import DecisionTreeRegressor
#If you do not pass estimator, it uses a decision tree regressor by default.
regressor = AdaBoostRegressor(
   # estimator=DecisionTreeRegressor(max_depth=3),
    n_estimators=100,
    learning_rate=0.1,
   # loss='linear',
    random_state=42
)

#sklearn is telling you that you passed a single column as a 2D column vector instead of a 1D target arra
# Tofix this issue  use ravel() - Flattens that array into 1 dimension.
Y = y_train.values.ravel()

regressor.fit(x_train, Y)

AdaBoostRegressor(learning_rate=0.1, n_estimators=100, random_state=42)

In [22]:
# Uses the trained model to predict output values for the test inputs
y_pred = regressor.predict(x_test)
# Prints those predicted values
#y_pred

In [23]:
# Imports the R² score function.
from sklearn.metrics import r2_score
# Calculates the R² value comparing actual (y_test) vs predicted (y_pred).
score = r2_score(y_test, y_pred)
# Print r2_score
score

0.8563390763191072